### ISSUE TITLE
Character controller collides with sensor colliders (Typescript)

### ISSUE THREAD

**Issue by Luis-Enrique93** [dimforge/rapier.js#242] opened 2023-07-17 18:46 UTC
Built in Character controller collides with sensor colliders

package: @dimforge/rapier3d
version: 0.11.2

**Comment by vivax3794** [comment] 2023-07-29 11:16
I have the same issue with a sensor collider in Bevy.

**Comment by Sceat** [comment] 2023-12-19 01:56
This defeats the purpose of sensor, issue still there :/

**Comment by khudiiash** [comment] 2024-05-11 13:38
And the issue is still there, cannot use sensors at all

**Comment by sebcrozet** [comment] 2024-05-11 14:30
The character controller takes an optional `filterFlags?: QueryFilterFlags` argument. To exclude sensors, simply specify `QueryFilterFlags.EXCLUDE_SENSORS`:
```rust
characterController.computeColliderMovement(collider, desiredMovement, QueryFilterFlags.EXCLUDE_SENSORS);
```

Closing this now since this is a usage issue.
Please reopen if excluding the sensors this way doesn’t work as expected.

**Closed by sebcrozet** 2024-05-11 14:30 UTC

**Comment by vivax3794** [comment] 2024-05-21 09:27
I will say I would have expected that to be the default (as it is how sensors interact with other types of colliders), but thanks for pointing us in the right direction. Maybe it is worth mentioning on the characther controller guides that they collide with sensors by default?
