### ISSUE TITLE
about ams.js version

### ISSUE THREAD

**Issue by 313364973** [dimforge/rapier.js#169] opened 2022-10-22 06:16 UTC
My js environment is not support for webassembly ,but I still want use rapier。
So is it posible to compile webassembly version to ams.js version。
If so and the Cross-platform determinism feature of the ams.js version still work?
thanks a lot

**Comment by sebcrozet** [comment] 2022-10-31 09:22
Closing this as duplicate of #175

**Closed by sebcrozet** 2022-10-31 09:22 UTC
