### ISSUE TITLE
JS Bindings Demo (2D & 3D) Playback Speed Issues

### ISSUE THREAD

**Issue by BraidenPsiuk** [dimforge/rapier.js#92] opened 2022-03-15 17:28 UTC
Hello, the [2D Demos](https://rapier.rs/demos2d/index.html) and [3D Demos](https://rapier.rs/demos3d/index.html) seem to run fine at first glance, but selecting a different "demo" from the dropdown seems to double the speed of the simulation.

I noticed that the speed seems to be reset when selecting the "keva tower" 3D demo and then switching to another demo.

Also you can quickly reproduce this issue by pressing "restart" multiple times.

**Comment by jcyuan** [comment] 2022-03-31 04:24
that seems bugs in the testbed, lib actually works fine

**Comment by sebcrozet** [comment] 2022-06-22 07:44
I believe that the issue was caused by the way our webworker was setup. It should be fixed now (I haven’t uploaded updated demos for a while). Please reopen if you still observe this problem.

**Closed by sebcrozet** 2022-06-22 07:44 UTC
